CREATE TABLE IF NOT EXISTS `ball_lap_times` (
  `ID` INTEGER PRIMARY KEY AUTOINCREMENT,
  `SESSION_ID` int(10) NOT NULL,
  `TIME` varchar(255) NOT NULL
)

CREATE TABLE IF NOT EXISTS `clockwise` (
  `ID` INTEGER PRIMARY KEY AUTOINCREMENT,
  `CLOCKWISE` int(11) NOT NULL,
  `SESSION_ID` int(11) NOT NULL
)

CREATE TABLE IF NOT EXISTS `outcomes` (
  `ID` INTEGER PRIMARY KEY AUTOINCREMENT,
  `SESSION_ID` int(10) NOT NULL,
  `NUMBER` varchar(255) NOT NULL,
  `OBSTACLES` int(10) NOT NULL
)

CREATE TABLE IF NOT EXISTS `session` (
  `ID` INTEGER PRIMARY KEY AUTOINCREMENT
)

CREATE TABLE IF NOT EXISTS `wheel_lap_times` (
  `ID` INTEGER PRIMARY KEY AUTOINCREMENT,
  `SESSION_ID` int(10) NOT NULL,
  `TIME` varchar(255) NOT NULL
)

CREATE TABLE IF NOT EXISTS `session` (
  `ID` INTEGER PRIMARY KEY AUTOINCREMENT
)